(* Auto-generated by elimrel.helly_checker. *)

module Solver = struct
  type sort_areality =
    | Global
    | Regional
    | Local
    | Borrowed

  type sort_contention =
    | Uncontended
    | Shared
    | Contended

  type sort_linearity =
    | Many
    | Once
    | Never

  type sort_portability =
    | Portable
    | Nonportable

  type sort_uniqueness =
    | Unique
    | Aliased
    | Taken
end
